version: '3'
services:
  psv:
    build:
      context: ./src/Backend
      dockerfile: Dockerfile
    volumes:
      - ./src/Backend:/app
      - ./envs:/app/envs
    ports:
      - 5000:5000

  web:
    build:
      context: ./src/Frontend
      dockerfile: Dockerfile
    volumes:
      - ./src/Frontend:/app
    ports:
      - 3000:3000

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 8080:80
    depends_on:
      - psv
      - web