version: '3'
services:
  updater:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    volumes:
      - ./src/backend:/app
    ports:
      - 5000:5000

  web:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    volumes:
      - ./src/frontend:/app
    ports:
      - 8080:80
    depends_on:
      - updater